language: objective-c
osx_image: xcode7.3
cache:
- bundler
- cocoapods
script:
- xcodebuild -scheme AlamofireXMLRPC -workspace AlamofireXMLRPC.xcworkspace -sdk macosx10.11 build test
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'AlamofireXMLRPC'