language: objective-c
osx_image: xcode7.3
cache:
- bundler
- cocoapods
xcode_workspace: AlamofireXMLRPC.xcworkspace
xcode_scheme: AlamofireXMLRPC
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'AlamofireXMLRPC'