language: objective-c
osx_image: xcode7.3
before_install:
  - gem install activesupport -v 4.2.6
  - gem install cocoapods
script: xctool -workspace AlamofireXMLRPC.xcworkspace sdk macosx10.11 -scheme Pods-AlamofireXMLRPC test